config/routes.rb
Reservations::Application.routes.draw do
  root :to => 'catalog#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "log/index"
  get "log/version/:id" => "log#version", as: :version_view
  get "log/history/:object_type/:id" => "log#history", as: :history

  get "status/index"

  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :documents,
            :requirements

  resources :equipment_objects, concerns: :deactivatable

  resources :announcements, except: [:show]

  resources :categories, concerns: :deactivatable do
    resources :equipment_models
  end

  resources :equipment_models, concerns: :deactivatable do
    resources :equipment_objects
  end

  get '/import_users/import' => 'import_users#import_page', :as => :csv_import_page
  post '/import_users/imported' => 'import_users#import', :as => :csv_imported

  resources :users do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search' => 'catalog#search', :as => :catalog_search # what kind of http request is this?
  get '/markdown_help' => 'application#markdown_help', :as => :markdown_help

  resources :reservations do
    member do
      get :checkout_email
      get :checkin_email
      put :renew
    end
  end

  get '/blackouts/flash_message' => 'blackouts#flash_message', :as => :flash_message
  get '/blackouts/new_recurring' => 'blackouts#new_recurring', :as => :new_recurring_blackout

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  # reservations views
  get '/reservations/manage/:user_id' => 'reservations#manage', :as => :manage_reservations_for_user
  get '/reservations/current/:user_id' => 'reservations#current', :as => :current_reservations_for_user

  get '/reservations/review/:id' => 'reservations#review', :as => :review_request
  put '/reservations/approve/:id' => 'reservations#approve_request', :as => :approve_request
  put '/reservations/deny/:id' => 'reservations#deny_request', :as => :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id' => 'reservations#checkout', :as => :checkout
  put '/reservations/check-in/:user_id' => 'reservations#checkin', :as => :checkin

  put '/catalog/update_view' => 'catalog#update_user_per_cat_page', :as => :update_user_per_cat_page
  get '/catalog' => 'catalog#index', :as => :catalog
  put '/add_to_cart/:id' => 'catalog#add_to_cart', :as => :add_to_cart
  put '/remove_from_cart/:id' => 'catalog#remove_from_cart', :as => :remove_from_cart
  delete '/cart/empty' => 'application#empty_cart', :as => :empty_cart
  put '/cart/update' => 'application#update_cart', :as => :update_cart

  get '/reports/index' => 'reports#index', :as => :reports
  get '/reports/:id/for_model' => 'reports#for_model', :as => :for_model_report

  get '/reports/for_model_set' => 'reports#for_model_set', :as => :for_model_set_reports # what http request? old match
  post '/reports/update' => 'reports#update_dates', :as => :update_dates # what http request? old match
  post '/reports/generate' => 'reports#generate', :as => :generate_report

  get '/logout' => 'application#logout', :as => :logout # what kind of http request is this? old match

  get '/terms_of_service' => 'application#terms_of_service', :as => :tos # change match to get?

  # yes, both of these are needed to override rails defaults of /controller/:id/edit
  get '/app_configs/' => 'app_configs#edit', :as => :edit_app_configs # match
  resources :app_configs, :only => [:update]

  get '/new_admin_user' => 'application_setup#new_admin_user', :as => :new_admin_user
  post '/create_admin_user' => 'application_setup#create_admin_user', :as => :create_admin_user
  resources :application_setup, :only => [:new_admin_user, :create_admin_user]

  get '/new_app_configs' => 'application_setup#new_app_configs', :as => :new_app_configs
  post '/create_app_configs' => 'application_setup#create_app_configs', :as => :create_app_configs

  get 'contact' => 'contact#new', :as => 'contact_us'
  post 'contact' => 'contact#create', :as => 'contact_submitted'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get 'status' => 'status#index'

  get ':controller(/:action(/:id(.:format)))' #wtf match is this

  # this is a fix for running letter opener inside vagrant
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/equipment_object.rb
class EquipmentObject < ActiveRecord::Base

  include Searchable

  has_paper_trail

  belongs_to :equipment_model
  has_one :category, through: :equipment_model
  has_many :reservations

  validates :name,
            :equipment_model, presence: true

  nilify_blanks only: [:deleted_at]

  # table_name is needed to resolve ambiguity for certain queries with 'includes'
  scope :active, lambda { where("#{table_name}.deleted_at is null") }

  searchable_on(:name, :serial)

  def status
    if self.deleted? and self.deactivation_reason
      "Deactivated (#{self.deactivation_reason})"
    elsif self.deleted?
      "Deactivated"
    elsif r = self.current_reservation
      "checked out by #{r.reserver.name} through #{r.due_date.strftime("%b %d")}"
    else
      "available"
    end
  end

  def current_reservation
    self.reservations.each do |r|
      return r if r.checked_out && r.checked_in.nil?
    end
    return nil
  end

  def available?
    status == "available"
  end

  def self.for_eq_model(model_id,source_objects)
    # count the number of equipment objects for a given
    # model out of an array of source objects
    # 0 queries

    count = 0
    source_objects.each do |o|
      count += 1 if o.equipment_model_id == model_id
    end
    count
  end

end

app/controllers/equipment_objects_controller.rb
class EquipmentObjectsController < ApplicationController
  load_and_authorize_resource
  before_action :set_current_equipment_object, only: [:show, :edit, :update, :destroy, :deactivate, :activate]
  before_action :set_equipment_model_if_possible, only: [:index, :new]

  include ActivationHelper

  # ---------- before filter methods ---------- #

  def set_current_equipment_object
    @equipment_object = EquipmentObject.find(params[:id])
  end

  def set_equipment_model_if_possible
    @equipment_model = EquipmentModel.find(params[:equipment_model_id]) if params[:equipment_model_id]
  end

  # ---------- end before filter methods ---------- #

  #I'm not sure if there's ever a way @equipment_model could be set?
  def index
    if params[:show_deleted]
      @equipment_objects = ( @equipment_model  ? @equipment_model.equipment_objects : EquipmentObject.all )
    else
      @equipment_objects = ( @equipment_model  ? @equipment_model.equipment_objects.active : EquipmentObject.active )
    end
  end

  def show
  end

  def new
    @equipment_object = EquipmentObject.new(equipment_model: @equipment_model)
  end

  def create
    @equipment_object = EquipmentObject.new(equipment_object_params)
    if @equipment_object.save
      flash[:notice] = "Successfully created equipment object. #{@equipment_object.serial}"
      redirect_to @equipment_object.equipment_model
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    p = equipment_object_params
    if p[:deleted_at].blank?
      # Delete deactivation reason when "Disabled?" is toggled
      p[:deactivation_reason] = ""
    end

    if @equipment_object.update_attributes(p)
      flash[:notice] = "Successfully updated equipment object."
      redirect_to @equipment_object.equipment_model
    else
      render action: 'edit'
    end
  end

  # Deactivate and activate extend controller methods in ApplicationController
  def deactivate
    @equipment_object.update_attributes(deactivation_reason: params[:deactivation_reason])
    super
  end

  def activate
    super
    @equipment_object.update_attributes(deactivation_reason: nil)
  end

  private

  def equipment_object_params
    params.require(:equipment_object).permit(:name, :serial, :equipment_model_id,
                                             :deleted_at, :deactivation_reason)
  end
end

app/helpers/equipment_objects_helper.rb
module EquipmentObjectsHelper
  def add_equipment_object_link(name)
    #TODO link_to_function is deprecated and this can probably be removed
    link_to_function name do |page|
      page.insert_html :bottom, :equipment_model_table, partial: 'equipment_object', object: EquipmentObject.new
    end
  end
end

app/views/equipment_objects/_equipment_object.html.erb
<% #TODO check if this can be removed %>
<tr class="equipment_object">
<%= fields_for "equipment_model[equipment_object_attributes][]", equipment_object do |equipment_object_form| %>
  <td>
    <%= equipment_object_form.text_field :name %>
  </td>
  <td>
    <%= equipment_object_form.text_field :serial %>
  </td>
  <td>
    new
  </td>
  <td>    
    <%= link_to_function "[remove]", "$(this).parents('.equipment_object').remove()" %>
  </td>
<% end %>
</tr>

app/views/equipment_objects/_form.html.erb
<%= simple_form_for @equipment_object, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.error_notification %>
  <%= f.association :equipment_model, placeholder: 'Please select an equipment model...' %>
  <%=f.input :name%>
  <%=f.input :serial%>
  <%=f.input :deleted_at, :as => :deleted, label: "Disabled"%>
  <%=f.input :deactivation_reason, label: "Reason for deactivation?"%>
  <%= f.button :wrapped, :cancel => equipment_objects_path %>
<% end %>

app/views/equipment_objects/edit.html.erb
<% title "Edit Equipment Item" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @equipment_object %> |
  <%= link_to "View All", equipment_objects_path %>
</p>

app/views/equipment_objects/index.html.erb
<% title (@equipment_model.nil? ? "Equipment Items" : @equipment_model.name.pluralize) %>

<table id="table_woo" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Equipment Model</th>
    <th>Item Name</th>
    <th>Serial (optional)</th>
    <th>Status</th>
<%# these blank TH's necessary for the sort function %>
  <% if can? :manage, EquipmentObject %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for equipment_object in @equipment_objects %>
    <tr>
      <td><%= link_to equipment_object.equipment_model.name, equipment_object.equipment_model %></td>
       <% if can? :manage, EquipmentObject %>
         <td><%= link_to equipment_object.name, equipment_object %></td>
       <% else %>
         <td> <%=equipment_object.name%> </td>
       <% end %>
      <td><%= equipment_object.serial %></td>

      <% current_res = equipment_object.current_reservation %>
      <td>
        <%= link_to_if current_res, equipment_object.status, current_res %>
      </td>

      <% if can? :manage, EquipmentObject %>
        <td><%= link_to "Edit", edit_equipment_object_path(equipment_object), :class => "btn" %></td>
        <td>
          <%= make_deactivate_btn(:equipment_objects,equipment_object) %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<hr />

<% if can? :manage, EquipmentObject %>

  <div class="form-actions">
    <% if @equipment_model %>
     <%= link_to ("New "+@equipment_model.name.singularize), new_equipment_model_equipment_object_path(@equipment_model) %>
     <%= link_to "View All Equipment Items", equipment_objects_path %>
    <% else %>
      <%= link_to "New Equipment Item", new_equipment_object_path, :class => "btn btn-primary" %>
    <% end %>

    <% if params[:show_deleted] %>
      <%= link_to "Hide Deactivated Items", equipment_objects_path, :class => "btn" %>
    <% else %>
      <%= link_to "Show Deactivated Items", equipment_objects_path(:show_deleted => true), :class => "btn" %>
    <% end %>
  </div>

<% end %>

app/views/equipment_objects/new.html.erb
<% title "Add New " + (@equipment_model.nil? ? "Equipment Items" : @equipment_model.name.pluralize) %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", (@equipment_model.nil? ? equipment_objects_path : equipment_model_equipment_objects_path(@equipment_model)) %></p>

app/views/equipment_objects/show.html.erb
<% title "Equipment Item for #{@equipment_object.equipment_model.name}" %>

<p>
  <strong>Name:</strong>
  <%= @equipment_object.name %>
</p>
<% unless @equipment_object.serial.nil? or @equipment_object.serial == "" %>
  <p>
    <strong>Serial:</strong>
    <%= @equipment_object.serial %>
  </p>
<% end %>
<p>
  <strong>Equipment Model:</strong>
  <%= link_to @equipment_object.equipment_model.name, @equipment_object.equipment_model %>
</p>
<p>
  <strong>Status:</strong>
  <%= @equipment_object.status %>
</p>
<div class="form-actions">
  <%= link_to "Edit", edit_equipment_object_path(@equipment_object), class: 'btn' %>
  <%= make_deactivate_btn :equipment_objects, @equipment_object %>
  <%= link_to "View All", equipment_objects_path, class: 'btn' %>
</div>