config/routes.rb
Reservations::Application.routes.draw do
  root :to => 'catalog#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "log/index"
  get "log/version/:id" => "log#version", as: :version_view
  get "log/history/:object_type/:id" => "log#history", as: :history

  get "status/index"

  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :documents,
            :requirements

  resources :equipment_objects, concerns: :deactivatable

  resources :announcements, except: [:show]

  resources :categories, concerns: :deactivatable do
    resources :equipment_models
  end

  resources :equipment_models, concerns: :deactivatable do
    resources :equipment_objects
  end

  get '/import_users/import' => 'import_users#import_page', :as => :csv_import_page
  post '/import_users/imported' => 'import_users#import', :as => :csv_imported

  resources :users do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search' => 'catalog#search', :as => :catalog_search # what kind of http request is this?
  get '/markdown_help' => 'application#markdown_help', :as => :markdown_help

  resources :reservations do
    member do
      get :checkout_email
      get :checkin_email
      put :renew
    end
  end

  get '/blackouts/flash_message' => 'blackouts#flash_message', :as => :flash_message
  get '/blackouts/new_recurring' => 'blackouts#new_recurring', :as => :new_recurring_blackout

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  # reservations views
  get '/reservations/manage/:user_id' => 'reservations#manage', :as => :manage_reservations_for_user
  get '/reservations/current/:user_id' => 'reservations#current', :as => :current_reservations_for_user

  get '/reservations/review/:id' => 'reservations#review', :as => :review_request
  put '/reservations/approve/:id' => 'reservations#approve_request', :as => :approve_request
  put '/reservations/deny/:id' => 'reservations#deny_request', :as => :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id' => 'reservations#checkout', :as => :checkout
  put '/reservations/check-in/:user_id' => 'reservations#checkin', :as => :checkin

  put '/catalog/update_view' => 'catalog#update_user_per_cat_page', :as => :update_user_per_cat_page
  get '/catalog' => 'catalog#index', :as => :catalog
  put '/add_to_cart/:id' => 'catalog#add_to_cart', :as => :add_to_cart
  put '/remove_from_cart/:id' => 'catalog#remove_from_cart', :as => :remove_from_cart
  delete '/cart/empty' => 'application#empty_cart', :as => :empty_cart
  put '/cart/update' => 'application#update_cart', :as => :update_cart

  get '/reports/index' => 'reports#index', :as => :reports
  get '/reports/:id/for_model' => 'reports#for_model', :as => :for_model_report

  get '/reports/for_model_set' => 'reports#for_model_set', :as => :for_model_set_reports # what http request? old match
  post '/reports/update' => 'reports#update_dates', :as => :update_dates # what http request? old match
  post '/reports/generate' => 'reports#generate', :as => :generate_report

  get '/logout' => 'application#logout', :as => :logout # what kind of http request is this? old match

  get '/terms_of_service' => 'application#terms_of_service', :as => :tos # change match to get?

  # yes, both of these are needed to override rails defaults of /controller/:id/edit
  get '/app_configs/' => 'app_configs#edit', :as => :edit_app_configs # match
  resources :app_configs, :only => [:update]

  get '/new_admin_user' => 'application_setup#new_admin_user', :as => :new_admin_user
  post '/create_admin_user' => 'application_setup#create_admin_user', :as => :create_admin_user
  resources :application_setup, :only => [:new_admin_user, :create_admin_user]

  get '/new_app_configs' => 'application_setup#new_app_configs', :as => :new_app_configs
  post '/create_app_configs' => 'application_setup#create_app_configs', :as => :create_app_configs

  get 'contact' => 'contact#new', :as => 'contact_us'
  post 'contact' => 'contact#create', :as => 'contact_submitted'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get 'status' => 'status#index'

  get ':controller(/:action(/:id(.:format)))' #wtf match is this

  # this is a fix for running letter opener inside vagrant
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  layout 'application_with_sidebar'

  before_filter :set_equipment_model, only: [:add_to_cart, :remove_from_cart]

  # --------- before filter methods --------- #

  def set_equipment_model
    @equipment_model = EquipmentModel.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    logger.error("Attempt to add invalid equipment model #{params[:id]}")
    flash[:notice] = "Invalid equipment_model"
    redirect_to root_path
  end

  # --------- end before filter methods --------- #


  def index
    @reserver_id = session[:cart].reserver_id
    prepare_pagination
    prepare_catalog_index_vars
  end

  def add_to_cart
    change_cart(:add_item, @equipment_model)
  end

  def remove_from_cart
    change_cart(:remove_item, @equipment_model)
  end

  def update_user_per_cat_page
    session[:items_per_page] = params[:items_per_page] if !params[:items_per_page].blank?
    respond_to do |format|
      format.html{redirect_to root_path}
      format.js{render action: "cat_pagination"}
    end
  end

  def search
    if params[:query].blank?
      redirect_to root_path and return
    else
      @equipment_model_results = EquipmentModel.active.catalog_search(params[:query])
      @category_results = Category.catalog_search(params[:query])
      @equipment_object_results = EquipmentObject.catalog_search(params[:query])
      prepare_catalog_index_vars(@equipment_model_results)
      render 'search_results' and return
    end
  end

  private
    # this method is called to either add or remove an item from the cart
    # it takes either :add_item or :remove_item as an action variable,
    # and adds or removes the equipment_model set from params{} in the before_filter.
    # Finally, it renders the root page and runs the javascript to update the cart
    # (or displays the appropriate errors)
    def change_cart(action, item)
      cart.send(action, item)
      errors = cart.validate_all
      flash[:error] = errors.to_sentence
      flash[:notice] = "Cart updated."

      respond_to do |format|
        format.html{redirect_to root_path}
        format.js{render template: "cart_js/update_cart"}
      end
    end

  def prepare_pagination
    array = []
    array << params[:items_per_page].to_i
    array << session[:items_per_page].to_i
    array << @app_configs.default_per_cat_page
    array << 10
    items_per_page = array.reject{ |a| a.blank? || a == 0 }.first
    # assign items per page to the passed params, the default or 10
    # depending on if they exist or not
    @per_page_opts = [10, 20, 25, 30, 50].unshift(items_per_page).uniq
    session[:items_per_page] = items_per_page
  end


end

app/views/catalog/_catalog_listing.html.erb
<% eq_models_by_category.each do |category, equipment_models| %>
      <% unless equipment_models.nil? %>
        <h2 class="catalog">
          <%= link_to category.name, category_equipment_models_path(category) %>
        </h2>
        <ul class="thumbnails">
        <% equipment_models.each do |equipment_model| %>
          <li class="span3">
          <%= render partial: 'equipment_model_div', locals: { equipment_model: equipment_model,
                                                               availability_hash: availability_hash,
                                                               available_string: available_string,
                                                              } %>
          </li>
        <% end %>
        </ul>
      <% end %>
    <% end %>

app/views/catalog/_equipment_model_div.html.erb
<div class="thumbnail">
  <%= link_to equipment_model do %>
    <% image_tag (equipment_model.photo.exists? ? equipment_model.photo.url(:thumbnail) : "no-image.gif") %>
  <% end %>
  <h3 class="equipment_title">
    <%= link_to equipment_model.name, equipment_model, class: 'equipment_title_link', rel: 'tooltip', title: equipment_model.name %>
  </h3>
  <div class="caption_cat">
    <hr class ="special-hr"/>
    <span class="giant-numbers span1" id="availability_<%= equipment_model.id %>">
      <%= availability_hash[equipment_model.id] %>
    </span>
    <p class="model_availability">
      <%= available_string %>
    </p>
    <hr class ="special-hr"/>
    <p class="equipment_descr">
      <%= markdown_to_plain_text(equipment_model.description) %><br/>
      <%= link_to "More Info", equipment_model, class: 'more_info' %>
    </p>
  </div>

  <div class = "add_to_cart_box">
    <% @restricted = equipment_model.model_restricted?(cart.reserver_id) %>
    <% if @restricted %>
      <%= button_tag "Add to Cart", class: "btn disabled add_to_cart_disabled"%>
      <%= link_to "#qualifications_modal", class: 'not-qualified-icon', rel: "tooltip", title: "Not Qualified (click for more info)", :"data-toggle" => 'modal' do %>
        <i class="fa fa-exclamation-triangle"></i>
      <% end %>
      <% elsif availability_hash[equipment_model.id] > 0 %>
      <%= link_to "Add to Cart", add_to_cart_path(equipment_model), :method => :put, :remote => true, :class => "btn add_to_cart" %>
    <% else %>
      <%= button_tag "Add to Cart", :class => "btn disabled add_to_cart_disabled"%>
    <% end %>
  </div>

  <% if @restricted %>
  <div id="qualifications_modal" class="modal hide fade">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">×</button>
      <h3>Qualification Required</h3>
    </div>
    <div class="modal-body">
      <p><%= Requirement.list_requirement_admins(User.find(cart.reserver_id), equipment_model) %></p>
    </div>
  </div>
  <% end %>


</div>

app/views/catalog/_no_equipment.html.erb
<p>
  <h3>No equipment found.
    <% if can? :manage, EquipmentModel %>
      Try creating some
      <%= link_to "Equipment Models", new_equipment_model_path %>
      first!
    <% end %>
  </h3>
</p>

app/views/catalog/cat_pagination.js.erb
location.reload(true);

app/views/catalog/index.html.erb
<% title "Catalog" %>

<div id = 'models_available'>
<% if @eq_models_by_category.empty? %>
  <%= render partial: 'no_equipment' %>
<% else %>
    <div class="row">
      <div id="pagination_line" class="span9">
        <%# for kaminari pagination %>
        <%= paginate @page_eq_models_by_category,
              params: {controller: 'catalog', action: 'index' } %>
        <%= form_tag update_user_per_cat_page_path,
              id: 'items_per_form', class: "form-inline pull-right",
              remote: true, method: 'put' do %>
          <%= label_tag "Items per page:" %>
          <%= select_tag :items_per_page,
                options_for_select(@per_page_opts, session[:items_per_page]),
                :class => 'span1 autosubmitme' %>
        <% end %>
      </div>
    </div>

  <div id="catalog_listing">
    <%= render partial: 'catalog_listing', locals: { eq_models_by_category: @eq_models_by_category, available_string: @available_string, availability_hash: @availability_hash } %>
  </div>
  <%= paginate @page_eq_models_by_category %>
<% end %>
</div>

app/views/catalog/search_results.html.erb
<% title %-Search results for "#{params[:query]}"- %>

<% unless @category_results.empty? %>
  <div class="row">
    <div class="span9">
      <h2>Category Results</h2>
    </div>
  </div>
  <div class="row">
    <% @category_results.each do |category| %>
      <div class="span3">
        <div class="well">
          <h3 class="catalog">
            <%# print category name %>
            <%= link_to category.name, category_equipment_models_path(category) %>
          </h3>
        </div>
      </div>
    <% end %>

  </div>

<% end %>

<% unless @equipment_model_results.empty? %>
  <% unless @category_results.empty? %>

  <div class="row">
    <div class="span9">
      <h2>Equipment Model Results</h2>
    </div>
  </div>
  <% end %>
  <ul class="thumbnails">
    <% @equipment_model_results.each do |equipment_model| %>
      <li class="span3">
        <%= render :partial => 'equipment_model_div', :locals => { :equipment_model => equipment_model, availability_hash: @availability_hash, available_string: @available_string } %>
      </li>
    <% end %>
  </ul>
<% end %>

<% unless @equipment_object_results.empty? %>
  <div class="row">
    <div class="span9">
      <h2>Equipment Item Results</h2>
    </div>
  </div>

  <div class="row">
    <% @equipment_object_results.each do |equipment_object| %>

    <div class="span4">
      <div class="well">
        <p>
          <strong>Model:</strong>
          <%= link_to equipment_object.equipment_model.name, equipment_model_path(equipment_object.equipment_model) %>
        </p>
        <p>
          <strong>Item:</strong>
          <%= equipment_object.name %> (<%= equipment_object.serial %>)
        </p>
        <p>
          <strong>Status:</strong>
          <% if equipment_object.available? %>
            <span class="label label-success eo-table">Available</span>
          <% else %>
            <span class="label label-danger eo-table">Not Available</span>
          <% end %>
        </p>
      </div>
    </div>

    <% end %>
  </div>

<% end %>