config/routes.rb
Reservations::Application.routes.draw do
  root :to => 'catalog#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "log/index"
  get "log/version/:id" => "log#version", as: :version_view
  get "log/history/:object_type/:id" => "log#history", as: :history

  get "status/index"

  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :documents,
            :requirements

  resources :equipment_objects, concerns: :deactivatable

  resources :announcements, except: [:show]

  resources :categories, concerns: :deactivatable do
    resources :equipment_models
  end

  resources :equipment_models, concerns: :deactivatable do
    resources :equipment_objects
  end

  get '/import_users/import' => 'import_users#import_page', :as => :csv_import_page
  post '/import_users/imported' => 'import_users#import', :as => :csv_imported

  resources :users do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search' => 'catalog#search', :as => :catalog_search # what kind of http request is this?
  get '/markdown_help' => 'application#markdown_help', :as => :markdown_help

  resources :reservations do
    member do
      get :checkout_email
      get :checkin_email
      put :renew
    end
  end

  get '/blackouts/flash_message' => 'blackouts#flash_message', :as => :flash_message
  get '/blackouts/new_recurring' => 'blackouts#new_recurring', :as => :new_recurring_blackout

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  # reservations views
  get '/reservations/manage/:user_id' => 'reservations#manage', :as => :manage_reservations_for_user
  get '/reservations/current/:user_id' => 'reservations#current', :as => :current_reservations_for_user

  get '/reservations/review/:id' => 'reservations#review', :as => :review_request
  put '/reservations/approve/:id' => 'reservations#approve_request', :as => :approve_request
  put '/reservations/deny/:id' => 'reservations#deny_request', :as => :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id' => 'reservations#checkout', :as => :checkout
  put '/reservations/check-in/:user_id' => 'reservations#checkin', :as => :checkin

  put '/catalog/update_view' => 'catalog#update_user_per_cat_page', :as => :update_user_per_cat_page
  get '/catalog' => 'catalog#index', :as => :catalog
  put '/add_to_cart/:id' => 'catalog#add_to_cart', :as => :add_to_cart
  put '/remove_from_cart/:id' => 'catalog#remove_from_cart', :as => :remove_from_cart
  delete '/cart/empty' => 'application#empty_cart', :as => :empty_cart
  put '/cart/update' => 'application#update_cart', :as => :update_cart

  get '/reports/index' => 'reports#index', :as => :reports
  get '/reports/:id/for_model' => 'reports#for_model', :as => :for_model_report

  get '/reports/for_model_set' => 'reports#for_model_set', :as => :for_model_set_reports # what http request? old match
  post '/reports/update' => 'reports#update_dates', :as => :update_dates # what http request? old match
  post '/reports/generate' => 'reports#generate', :as => :generate_report

  get '/logout' => 'application#logout', :as => :logout # what kind of http request is this? old match

  get '/terms_of_service' => 'application#terms_of_service', :as => :tos # change match to get?

  # yes, both of these are needed to override rails defaults of /controller/:id/edit
  get '/app_configs/' => 'app_configs#edit', :as => :edit_app_configs # match
  resources :app_configs, :only => [:update]

  get '/new_admin_user' => 'application_setup#new_admin_user', :as => :new_admin_user
  post '/create_admin_user' => 'application_setup#create_admin_user', :as => :create_admin_user
  resources :application_setup, :only => [:new_admin_user, :create_admin_user]

  get '/new_app_configs' => 'application_setup#new_app_configs', :as => :new_app_configs
  post '/create_app_configs' => 'application_setup#create_app_configs', :as => :create_app_configs

  get 'contact' => 'contact#new', :as => 'contact_us'
  post 'contact' => 'contact#create', :as => 'contact_submitted'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get 'status' => 'status#index'

  get ':controller(/:action(/:id(.:format)))' #wtf match is this

  # this is a fix for running letter opener inside vagrant
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Searchable
  searchable_on(:name)

  has_many :equipment_models, dependent: :destroy

  validates :name,                presence: true,
                                  uniqueness: true

  validates :max_per_user,
            :max_checkout_length,
            :max_renewal_length,
            :max_renewal_times,
            :renewal_days_before_due,
            :sort_order,
                                  numericality: {
                                    allow_nil: true,
                                    integer_only: true,
                                    greater_than_or_equal_to: 0 }

  nilify_blanks only: [:deleted_at]

  # table_name is needed to resolve ambiguity for certain queries with 'includes'
  scope :active, lambda { where("#{table_name}.deleted_at is null") }

  def maximum_per_user
    max_per_user || Float::INFINITY
  end

  def maximum_renewal_length
    max_renewal_length || 0
  end

  def maximum_renewal_times
    max_renewal_times || Float::INFINITY
  end

  def maximum_renewal_days_before_due
    renewal_days_before_due || Float::INFINITY
  end

  def maximum_checkout_length
    max_checkout_length || Float::INFINITY
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource
  before_filter :set_current_category, only: [:show, :edit, :update, :destroy]

  include ActivationHelper

  # --------- before filter methods -------- #
  def set_current_category
    @category = Category.find(params[:id])
  end
  # --------- end before filter methods -------- #

  def index
    if (params[:show_deleted])
      @categories = Category.all
    else
      @categories = Category.active
    end
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Successfully created category."
      redirect_to @category
    else
      flash[:error] = "Oops! Something went wrong with creating the category."
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:notice] = "Successfully updated category."
      redirect_to @category
    else
      render action: 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :max_per_user, :max_checkout_length,
                                     :deleted_at, :max_renewal_times, :max_renewal_length,
                                     :renewal_days_before_due, :sort_order)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :max_per_user, label: "Maximum per user", hint: "leave blank if unrestricted" %>
  <%= f.input :max_checkout_length, label: "Maximum checkout length", hint: "leave blank if unrestricted" %>
  <%= f.input :sort_order, :hint => "lowest at top" %>
  <%= f.input :deleted_at, label: "Inactive", :as => :deleted %>
  
  <strong>Default Renewal Options</strong>
  <%= f.input :max_renewal_times, label: 'Maximum number of times this item may be renewed', hint: 'Leave blank for unrestricted.' %>
  <%= f.input :max_renewal_length, label: 'Maximum time allotted for each renewal period', hint: 'Default is zero. Actual renewal period will depend on availability.' %>
  <%= f.input :renewal_days_before_due, label: 'How many days before the due date should the Renew button become available?', hint: 'Leave blank to give the option to renew at any time.' %>
  
  <%= f.error :base %>
  <%= f.button :wrapped, :cancel => categories_path %> 
<% end %>  

app/views/categories/edit.html.erb
<% title "Edit Category" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @category %> |
  <%= link_to "View All", categories_path %> |
  <%= link_to "Delete", @category, :confirm => 'Deleting this category will delete all related Equipment Models, Items, and reservations. Are you sure you want to do this?', :method => :delete %>
</p>

app/views/categories/index.html.erb
<% title "Categories" %>

<table id="table_woo" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Max Per User</th>
    <th>Max Checkout Length (days)</th>
    <th>Sort Order</th>
  <%# these blank TH's necessary for the sort function %>
  <% if can? :manage, Category %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for category in @categories %>
    <tr>
      <td><%= link_to category.name, category %></td>
      <td><%= intify category.max_per_user %></td>
      <td><%= intify category.max_checkout_length %></td>
      <td><%= category.sort_order %></td>
      <% if can? :manage, Category %>
       <td><%= link_to "Edit", edit_category_path(category), :class => "btn" %></td>
       <td>
         <%= make_deactivate_btn(:categories,category) %>
       </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<hr />

<div class="form-actions">
  <% if can? :manage, Category %>
    <%= link_to "New Category", new_category_path, :class => "btn btn-primary" %>
  <% end %>
  <% if params[:show_deleted] %>
    <%= link_to "Hide Old Categories from List", categories_path, :class => "btn" %>
  <% else %>
    <%= link_to "Show Old Categories in List", categories_path(:show_deleted => true), :class => "btn" %>
  <% end %>
</div>

app/views/categories/new.html.erb
<% title "Add New Category" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", categories_path %></p>

app/views/categories/show.html.erb
<% title "Category: "+@category.name %>

<div class="btn-group">
  <%= link_to "Add new #{@category.name.singularize} model".titleize, new_category_equipment_model_path(@category), class: 'btn' %>
  <%= link_to "View all #{@category.name.singularize} models".titleize, category_equipment_models_path(@category), class: 'btn' %>
</div>
<hr />

<p>
  <strong>Max Per User:</strong>
  <%= intify @category.max_per_user %>
</p>
<p>
  <strong>Max Checkout Length:</strong>
  <%= dayify @category.max_checkout_length %>
</p>
<p>
  <strong>Sort Order:</strong>
  <%= @category.sort_order %>
</p>
<p>
  <strong>Activated:</strong>
  <%= @category.deleted_at == nil %>
</p>

<% unless (@category.max_renewal_length.nil?) or (@category.max_renewal_times.nil?) %>
  <p>
    <strong>Default Maximum Renewal Period:</strong>
    <%= pluralize(@category.maximum_renewal_length, 'day') %>
  </p>
  <% unless @category.renewal_days_before_due.nil? %>
    <p>
      Items in this category are by default available for renewal <strong>
      <%= pluralize(@category.maximum_renewal_days_before_due, 'day') %>
      </strong> before the reservation due date.
    </p>
  <% else %>
    <p>
      By default, items in this category may be renewed <strong>at any time</strong>.
    </p>
  <% end %>
  <p>
    <strong>Default Maximum Renewals per Reservation:</strong>
    <%= intify @category.max_renewal_times %>
  </p>
<% else %>
  <p>
    <strong><em>By default, items in this category are not available for renewal.</em></strong>
  </p>
<% end %>

<% if can? :manage, Category %>
  <div class="form-actions">
    <%= link_to "Edit Category", edit_category_path(@category), class: 'btn' %>
    <%= make_deactivate_btn :categories, @category %>
    <%= link_to "View All Categories", categories_path, class: 'btn' %>
  </div>
<% end %>