config/routes.rb
Reservations::Application.routes.draw do
  root :to => 'catalog#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "log/index"
  get "log/version/:id" => "log#version", as: :version_view
  get "log/history/:object_type/:id" => "log#history", as: :history

  get "status/index"

  concern :deactivatable do
    member do
      put :deactivate
      put :activate
    end
  end

  resources :documents,
            :requirements

  resources :equipment_objects, concerns: :deactivatable

  resources :announcements, except: [:show]

  resources :categories, concerns: :deactivatable do
    resources :equipment_models
  end

  resources :equipment_models, concerns: :deactivatable do
    resources :equipment_objects
  end

  get '/import_users/import' => 'import_users#import_page', :as => :csv_import_page
  post '/import_users/imported' => 'import_users#import', :as => :csv_imported

  resources :users do
    collection do
      post :find
      post :quick_new
      post :quick_create
    end
    member do
      put :ban
      put :unban
    end
    get :autocomplete_user_last_name, on: :collection
  end

  get '/catalog/search' => 'catalog#search', :as => :catalog_search # what kind of http request is this?
  get '/markdown_help' => 'application#markdown_help', :as => :markdown_help

  resources :reservations do
    member do
      get :checkout_email
      get :checkin_email
      put :renew
    end
  end

  get '/blackouts/flash_message' => 'blackouts#flash_message', :as => :flash_message
  get '/blackouts/new_recurring' => 'blackouts#new_recurring', :as => :new_recurring_blackout

  resources :blackouts do
    collection do
      post :create_recurring
    end
    member do
      get :flash_message
      delete :destroy_recurring
    end
  end

  # reservations views
  get '/reservations/manage/:user_id' => 'reservations#manage', :as => :manage_reservations_for_user
  get '/reservations/current/:user_id' => 'reservations#current', :as => :current_reservations_for_user

  get '/reservations/review/:id' => 'reservations#review', :as => :review_request
  put '/reservations/approve/:id' => 'reservations#approve_request', :as => :approve_request
  put '/reservations/deny/:id' => 'reservations#deny_request', :as => :deny_request

  # reservation checkout / check-in actions
  put '/reservations/checkout/:user_id' => 'reservations#checkout', :as => :checkout
  put '/reservations/check-in/:user_id' => 'reservations#checkin', :as => :checkin

  put '/catalog/update_view' => 'catalog#update_user_per_cat_page', :as => :update_user_per_cat_page
  get '/catalog' => 'catalog#index', :as => :catalog
  put '/add_to_cart/:id' => 'catalog#add_to_cart', :as => :add_to_cart
  put '/remove_from_cart/:id' => 'catalog#remove_from_cart', :as => :remove_from_cart
  delete '/cart/empty' => 'application#empty_cart', :as => :empty_cart
  put '/cart/update' => 'application#update_cart', :as => :update_cart

  get '/reports/index' => 'reports#index', :as => :reports
  get '/reports/:id/for_model' => 'reports#for_model', :as => :for_model_report

  get '/reports/for_model_set' => 'reports#for_model_set', :as => :for_model_set_reports # what http request? old match
  post '/reports/update' => 'reports#update_dates', :as => :update_dates # what http request? old match
  post '/reports/generate' => 'reports#generate', :as => :generate_report

  get '/logout' => 'application#logout', :as => :logout # what kind of http request is this? old match

  get '/terms_of_service' => 'application#terms_of_service', :as => :tos # change match to get?

  # yes, both of these are needed to override rails defaults of /controller/:id/edit
  get '/app_configs/' => 'app_configs#edit', :as => :edit_app_configs # match
  resources :app_configs, :only => [:update]

  get '/new_admin_user' => 'application_setup#new_admin_user', :as => :new_admin_user
  post '/create_admin_user' => 'application_setup#create_admin_user', :as => :create_admin_user
  resources :application_setup, :only => [:new_admin_user, :create_admin_user]

  get '/new_app_configs' => 'application_setup#new_app_configs', :as => :new_app_configs
  post '/create_app_configs' => 'application_setup#create_app_configs', :as => :create_app_configs

  get 'contact' => 'contact#new', :as => 'contact_us'
  post 'contact' => 'contact#create', :as => 'contact_submitted'

  get 'announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement'

  get 'status' => 'status#index'

  get ':controller(/:action(/:id(.:format)))' #wtf match is this

  # this is a fix for running letter opener inside vagrant
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/equipment_model.rb
class EquipmentModel < ActiveRecord::Base
  include ApplicationHelper

  include Searchable
  searchable_on(:name, :description)

  nilify_blanks only: [:deleted_at]

  has_paper_trail

  # table_name is needed to resolve ambiguity for certain queries with 'includes'
  scope :active, lambda { where("#{table_name}.deleted_at is null") }

  ##################
  ## Associations ##
  ##################

  belongs_to :category
  has_and_belongs_to_many :requirements
  has_many :equipment_objects, dependent: :destroy
  has_many :documents
  has_many :reservations
  has_many :checkin_procedures, dependent: :destroy
  accepts_nested_attributes_for :checkin_procedures, \
                                reject_if: :all_blank, allow_destroy: true
  has_many :checkout_procedures, dependent: :destroy
  accepts_nested_attributes_for :checkout_procedures, \
                                reject_if: :all_blank, allow_destroy: true

  # Equipment Models are associated with other equipment models to help us recommend items that go together.
  # Ex: a camera, camera lens, and tripod
  has_and_belongs_to_many :associated_equipment_models,
    class_name: "EquipmentModel",
    association_foreign_key: "associated_equipment_model_id",
    join_table: "equipment_models_associated_equipment_models"

  ##################
  ## Validations  ##
  ##################

  validates :name,
            :description,
            :category,     presence: true
  validates :name,         uniqueness: true
  validates :late_fee,     :replacement_fee,
                           numericality: { greater_than_or_equal_to: 0 }
  validates :max_per_user,
            :max_checkout_length, numericality: { allow_nil: true, \
                                              only_integer: true, \
                                              greater_than_or_equal_to: 1 }
  validates :max_renewal_length,
            :max_renewal_times,
            :renewal_days_before_due,  numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }

  validate :not_associated_with_self

  def not_associated_with_self
    unless self.associated_equipment_models.where(id: self.id).blank?
      errors.add(:associated_equipment_models, "You cannot associate a model with itself. Please deselect " + self.name)
    end
  end

  #################
  ## Paperclip   ##
  #################

  has_attached_file :photo, #generates profile picture
      styles: {
        large: { geometry: "500x500", format: "png" },
        medium: { geometry: "250x250", format: "png" },
        small: { geometry: "150x150", format: "png" },
        thumbnail: { geometry: "260x180", format: "png" } },
      convert_options: {
        large: '-background none -gravity center -extent 500x500',
        medium: '-background none -gravity center -extent 250x250',
        small: '-background none -gravity center -extent 150x150',
        thumbnail: '-background none -gravity center -extent 260x180' },
      url:  "/attachments/equipment_models/:attachment/:id/:style/:basename.:extension",
      path: ":rails_root/public/attachments/equipment_models/:attachment/:id/:style/:basename.:extension",
      default_url: "/fat_cat.jpeg",
      preserve_files: true


  has_attached_file :documentation, #generates document
      content_type: 'application/pdf',
      url: "/attachments/equipment_models/:attachment/:id/:style/:basename.:extension",
      path: ":rails_root/public/attachments/equipment_models/:attachment/:id/:style/:basename.:extension",
      preserve_files: true

  validates_attachment_content_type :photo,
      content_type: ["image/jpg", "image/png", "image/jpeg"],
      message: "must be jpeg, jpg, or png."
  validates_attachment_size         :photo,
      less_than: 1.megabytes,
      message: "must be less than 1 MB in size"
  validates_attachment :documentation, content_type: { content_type: "application/pdf" }

  Paperclip.interpolates :normalized_photo_name do |attachment, style|
    attachment.instance.normalized_photo_name
  end

  def normalized_photo_name
    "#{self.id}-#{self.photo_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')}"
  end

  ###################
  ## Class Methods ##
  ###################

  #TODO: this appears to be dead code - verify and remove
  def self.select_options
    self.order('name ASC').collect{|item| [item.name, item.id]}
  end

  ######################
  ## Instance Methods ##
  ######################

  #inherits from category if not defined

  def maximum_checkout_length
    max_checkout_length || category.maximum_checkout_length
  end

  def maximum_per_user
    max_per_user || category.maximum_per_user
  end

  def maximum_renewal_length
    max_renewal_length || category.maximum_renewal_length
  end

  def maximum_renewal_times
    max_renewal_times || category.maximum_renewal_times
  end

  def maximum_renewal_days_before_due
    renewal_days_before_due || category.maximum_renewal_days_before_due
  end

  # TODO: This appears to be dead code, verify and delete
  def document_attributes=(document_attributes)
    document_attributes.each do |attributes|
      documents.build(attributes)
    end
  end

  def num_reserved(start_date, due_date, source_reservations)
    # get the number reserved in the source reservations
    # uses 0 queries, you need to specify the max number of
    # items yourself
    max_reserved = 0
    start_date.to_date.upto(due_date.to_date) do |d|
      reserved = Reservation.number_for_model_on_date(d,self.id,source_reservations)
      if reserved > max_reserved
        max_reserved = reserved
      end
    end
    return max_reserved
  end

  def num_available_from_source(start_date, due_date, source_reservations)
    # get the number available in the given date range
    # take an array of reservations instead of using a database call
    # for database query optimization purposes
    # 2 queries to calculate max_num
    max_num = self.equipment_objects.active.count - number_overdue
    available = max_num - num_reserved(start_date,due_date, source_reservations)
    return available < 0 ? 0 : available
  end

  def num_available(start_date, due_date)
    # for if you just want the number available, 1 query to get
    # relevant reservations
    relevant_reservations = Reservation.for_eq_model(self).
      reserved_in_date_range(start_date.to_datetime, due_date.to_datetime).
      not_returned.all
    num_available_from_source(start_date, due_date, relevant_reservations)
  end

  # Returns true if the reserver is ineligible to checkout the model.
  def model_restricted?(reserver_id)
    reserver = User.find(reserver_id)
    !(self.requirements - reserver.requirements).empty?
  end

  # Returns the number of overdue objects for a given model,
  # as long as they have been checked out.
  def number_overdue
    Reservation.overdue.for_eq_model(self).size
  end


  def available_count(date)
    # get the total number of objects of this kind
    # then subtract the total quantity currently reserved, checked-out, and overdue
    total = equipment_objects.active.count
    reserved = Reservation.reserved_on_date(date).not_returned.for_eq_model(self).count
    total - reserved - number_overdue
  end

  def available_object_select_options
    self.equipment_objects.includes(:reservations).active.select{|e| e.available?}\
        .sort_by(&:name)\
        .collect{|item| "<option value=#{item.id}>#{item.name}</option>"}\
        .join.html_safe
  end

end

app/controllers/equipment_models_controller.rb
class EquipmentModelsController < ApplicationController
  layout 'application_with_sidebar', only: :show
  load_and_authorize_resource
  before_action :set_equipment_model, only: [:show, :edit, :update, :destroy]
  before_action :set_category_if_possible, only: [:index, :new]

  include ActivationHelper

  # --------- before filter methods --------- #
  def set_equipment_model
    @equipment_model = EquipmentModel.find(params[:id])
  end
  def set_category_if_possible
    @category = Category.find(params[:category_id]) if params[:category_id]
  end
  # --------- end before filter methods --------- #


  def index
    if params[:show_deleted]
      @equipment_models = ( @category ? @category.equipment_models : EquipmentModel.all )
    else
      @equipment_models = ( @category ? @category.equipment_models.active : EquipmentModel.active )
    end
  end

  def show
    @associated_equipment_models = @equipment_model.associated_equipment_models.sample(6)

    calendar_length = 1.month

    @reservation_data = []
    Reservation.active.for_eq_model(@equipment_model).each do |r|
      @reservation_data << {
        start: r.start_date,
        end: (r.status == 'overdue' ? Date.current + calendar_length : r.due_date) }
      # the above code mimics the current available? setup to show overdue
      # equipment as permanently 'out'.
    end

    @blackouts = []
    Blackout.active.each do |b|
      @blackouts << {
        start: b.start_date, end: b.end_date}
    end
    @date = Time.current.to_date
    @date_max = @date + calendar_length - 1.week
    @max = @equipment_model.equipment_objects.active.count

    @restricted = @equipment_model.model_restricted?(cart.reserver_id)
  end

  def new
    @equipment_model = EquipmentModel.new(category: @category)
  end

  def create
    @equipment_model = EquipmentModel.new(equipment_model_params)
    if @equipment_model.save
      flash[:notice] = "Successfully created equipment model."
      redirect_to @equipment_model
    else
      flash[:error] = "Please review the errors below. "
      render action: 'new'
    end
  end

  def edit
  end

  def delete_files
    # for a given filetype affected by param value, the file in question is saved in path contained value
    types = {"clear_documentation" => "documentations", "clear_photo" => "photos"}

    # only keep pairs that occur as keys with non-nil values in params
    types.select! {|k,v| params.keys.member? (k) and !v.nil?}
    types.each do |k,path|
      # TODO: investigate a way to do this without hard-coded paths
      # recursively remove files from filesystem
      file_location = Rails.root.to_s + "/public/attachments/equipment_models/" + path + "/" + @equipment_model.id.to_s + "/original/"
      FileUtils.rm_r file_location
      @equipment_model.documentation_file_name = NIL
    end
  end

  def update
    delete_files

    if @equipment_model.update_attributes(equipment_model_params)
      # hard-delete any deleted checkin/checkout procedures
      delete_procedures(params, "checkout")
      delete_procedures(params, "checkin")
      flash[:notice] = "Successfully updated equipment model."
      redirect_to @equipment_model
    else
      render action: 'edit'
    end
  end

  private

    # function to check for deleted checkin/checkout procedures and hard-delete them after equipment model update
    def delete_procedures(params, phase)
      # phase needs to be equal to either "checkout" or "checkin"
      phase_params = params[:equipment_model][:"#{phase}_procedures_attributes"]
      unless phase_params.nil?
        phase_params.each do |k, v|
          if v["id"] and v["_destroy"] != "false"
            @equipment_model.send(:"#{phase}_procedures")[k.to_i].destroy(:force)
          end
        end
      end
    end

    def equipment_model_params
      params.require(:equipment_model).
             permit(:name, :category_id, :category, :description, :late_fee,
                    :replacement_fee, :max_per_user, :document_attributes,
                    :deleted_at, :checkout_procedures_attributes,
                    :checkin_procedures_attributes, :photo, :documentation,
                    :max_renewal_times, :max_renewal_length,
                    :renewal_days_before_due, :associated_equipment_model_ids,
                    :requirement_ids, :requirements, :max_checkout_length)
    end
end

app/helpers/equipment_models_helper.rb
module EquipmentModelsHelper

  def evaluate_img_presence equipment_model
    if equipment_model.photo.exists?
      equipment_model.photo.url(:small)
    else
      "no-image-260.gif"
    end
  end

end

app/views/equipment_models/_add_to_cart.html.erb
  <% if @restricted %>
    <%= link_to "#qualifications_modal",
      class: 'not-qualified-icon-em',
      rel: "tooltip",
      title: 'Not Qualified (click for more info)',
      :"data-toggle" => 'modal' do %>
        <span class="fa fa-exclamation-triangle"></span>
     <% end %>
     <%= button_tag "Add to Cart", remote: true, class: 'btn btn-primary btn-large disabled' %>
     <div id="qualifications_modal" class="modal hide fade">
       <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h3><%= "Qualification Required" %></h3>
       </div>
       <div class="modal-body">
         <p>
           <%= Requirement.list_requirement_admins(current_user, @equipment_model)%>
         </p>
      </div>
    </div>
   <% else %>

     <%= link_to "Add to Cart", {:url => add_to_cart_path(@equipment_model)},
                                 :href => add_to_cart_path(@equipment_model),
                                 :method => :put, :remote => true, :class => 'btn btn-primary btn-large' %>
   <% end %>

app/views/equipment_models/_calendar.html.erb
  <h3>Availability</h3>
  <div id="reservation-calendar">
    <%= content_tag "div", id: "res-data", data:{url:@reservation_data, blackouts:@blackouts, today:@date.to_s, max:@max, date_max: @date_max.to_s} do %>
    <% end %>
    <div class = "month"><h4></h4></div>

    <ul id="calendar-ul">
      <li class = "calendar_cell" id ="<%= cart.start_date.to_date %>">
        <% for d in 0...6 %>
          <div class = "head"><strong></strong><i></i></div>
        <div class = "num"><h2></h2></div>
      </li>
      <li class = "calendar_cell">
      <% end %>
      <div class = "head"><strong></strong><i></i></div>
        <div class = "num"><h2></h2></div>
      </li>
    </ul>

    <div class = "controls c-left">
      <i class="fa control fa-angle-double-left fa-2x" change="-7" title="Move back a week"></i>
      <i class="fa control lite fa-angle-left fa-2x" change="-1" title="Move back a day"></i>
    </div>
    <div class = "controls c-right">
      <i class="fa control lite fa-angle-right fa-2x" change="1" title="Move forward a day"></i>
      <i class="fa control fa-angle-double-right fa-2x" change="7" title="Move forward a week"></i>
    </div>
</div>

app/views/equipment_models/_checkin_procedure_fields.html.erb
<div class="checkin_procedure, nested-fields">
<%= f.input :step, :wrapper => :append do %>
  <%= f.input_field :step %><%= link_to_remove_association "Remove Step", f, :class => "btn" %>
<% end %>
</div>

app/views/equipment_models/_checkout_procedure_fields.html.erb
<div class="checkout_procedure, nested-fields">
  <%= f.input :step, :wrapper => :append do %>
    <%= f.input_field :step %><%= link_to_remove_association "Remove Step", f, :class => "btn" %>
  <% end %>
</div>

app/views/equipment_models/_equipment_objects_table.html.erb
<table id="table_woo" class="datatable table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <th>Serial (optional)</th>
    <th>Status</th>
<%# these blank TH's necessary for the sort function %>
  <% if can? :manage, EquipmentObject %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for equipment_object in @equipment_model.equipment_objects %>
    <tr>
      <td><%= link_to equipment_object.name, equipment_object %></td>
      <td><%= equipment_object.serial %></td>
      <% if equipment_object.status == "available" %>
        <td><span class="label label-success eo-table">Available</span></td>
      <% else %>
        <% current_res = equipment_object.current_reservation %>
        <td><%= link_to_if current_res, equipment_object.status, current_res %></td>
      <% end %>
      <% if can? :manage, EquipmentObject %>
        <td><%= link_to "Edit", edit_equipment_object_path(equipment_object), :class => "btn" %></td>
        <td>
          <%= make_deactivate_btn(:equipment_objects,equipment_object) %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/equipment_models/_form.html.erb
<%= simple_form_for @equipment_model, html: { multipart: true, class:
  "form-horizontal" } do |f| %>

  <%= f.error_notification %>
  <%= f.association :category, hint: "#{link_to "Add New Category", new_category_path, class: "btn"}".html_safe,
  placeholder: 'Select a Category' %>

  <input class="hidden" id="category" name="MODELNAME[category]" type="hidden">

  <%= f.association :associated_equipment_models, input_html: {class: 'input-xlarge'},
  placeholder: 'Start typing an equipment model name', collection:
  EquipmentModel.where("id != ?", params[:id]) %>

  <%# TODO: review this. do we want it here? %>
  <%#= f.association :requirements, input_html: {class: 'input-xlarge select2-input select2-focused', id:'requirement_equipment_model'},
  placeholder: 'Start typing an equipment model name', collection: Requirement.all.map{|req| [req.description,req.id]} %>

  <%= f.input :name %>

  <%= f.input :description, as: :text, hint: "#{render :partial => 'shared/markdown_button'}".html_safe %>

  <%= f.input :late_fee, wrapper: :prepend do %>
    <%= content_tag :span, "$", class: "add-on" %><%= f.input_field :late_fee,
    class: 'input-small', value: number_with_precision(f.object.late_fee,
    precision: 2), type: 'number', step: 'any' %>
  <% end %>

  <%= f.input :replacement_fee, wrapper: :prepend do %>
    <%= content_tag :span, "$", class: "add-on" %><%= f.input_field :replacement_fee,
    class: 'input-small', value: number_with_precision(f.object.replacement_fee,
    precision: 2), type: 'number', step: 'any' %>
  <% end %>

  <%= f.input :max_per_user, label: "Maximum per user", hint:
  "Leave blank to default to category value.", input_html: {class: 'input-small'} %>

  <%= f.input :deleted_at, label: "Inactive", as: :deleted, hint:
  'Make this equipment model unavailable for checkout.' %>

  <%= f.input :max_checkout_length, label: 'Maximum time alloted for each checkout period',
    hint: 'Leave blank to default to category value.' %>

    <fieldset>
    <legend>Renewal Options</legend>
    <%= f.input :max_renewal_times, label: 'Maximum number of times this item may be renewed',
    hint: 'Leave blank to default to category value.', wrapper: :append do %>
      <%= f.input_field :max_renewal_times, class: 'input-small', type: 'number' %><%=
      content_tag :span, "times", class: "add-on" %>
    <% end %>

    <%= f.input :max_renewal_length, label: 'Maximum time allotted for each renewal period',
    hint: 'Leave blank to default to category value. Actual renewal period will depend on availability.',
    wrapper: :append do %>
      <%= f.input_field :max_renewal_length, class: 'input-small', type: 'number' %><%=
      content_tag :span, "days", class: "add-on" %>
    <% end %>



    <%= f.input :renewal_days_before_due, label:
    'How many days before the due date should the Renew button become available?',
    hint: 'Leave blank to default to category value.', wrapper: :append do %>
      <%= f.input_field :renewal_days_before_due, class: 'input-small', type: 'number' %><%=
      content_tag :span, "days", class: "add-on" %>
    <% end %>
  </fieldset>

  <fieldset>
    <p><legend>Checkout Procedures</legend></p>
    <%= f.simple_fields_for :checkout_procedures do |procedure| %>
      <%= render 'checkout_procedure_fields', f: procedure %>
    <% end %>
    <div class="links">
      <p><%= link_to_add_association 'Add Step', f, :checkout_procedures,
      class: "btn" %></p>
    </div>
  </fieldset>

  <fieldset>
    <p><legend>Checkin Procedures</legend></p>
    <%= f.simple_fields_for :checkin_procedures, wrapper: :append do |procedure| %>
      <%= render 'checkin_procedure_fields', f: procedure %>
    <% end %>
    <div class="links">
      <p><%= link_to_add_association 'Add Step', f, :checkin_procedures,
      class: "btn" %></p>
    </div>
  </fieldset>

  <fieldset>
    <legend>Media</legend>
    <%# Paperclip inline error fix %>
    <%= f.input :photo, label: "Upload Photo", wrapper_html: {class:
    paperclip_field_error(f, :photo_content_type, :photo_file_size)} do %>
      <%= f.input_field :photo, as: :file %>
      <%= f.error :photo_content_type %>
      <%= f.error :photo_file_size %>
    <% end %>
    <% unless @equipment_model.photo_file_name.nil? %>
      <div class='control-group'>
        <div class="controls">

          <%= image_tag @equipment_model.photo.url(:thumbnail) %>
          <%= label_tag 'clear_photo' do %>
            <%= check_box_tag 'clear_photo', nil, false %>
            <%= 'Delete current photo?' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%# Paperclip inline error fix %>
    <%= f.input :documentation, label: "Upload Documentation", wrapper_html: {class:
      paperclip_field_error(f, :documentation_content_type, :documentation_file_size)} do %>
      <%= f.input_field :documentation, as: :file %>
      <%= f.error :documentation_content_type %>
      <%= f.error :documentation_file_size %>
    <% end %>
    <% unless @equipment_model.documentation_file_name.nil? %>
      <div class='control-group'>
        <div class="controls">

          <p>
            <h4>
              <%= (link_to @equipment_model.documentation_file_name, @equipment_model.documentation.url, target: "_blank") if @equipment_model.documentation.exists? %>
            </h4>
          </p>
          <%= label_tag 'clear_documentation' do %>
            <%= check_box_tag 'clear_documentation', nil, false %>
            <%= 'Delete current documentation?' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </fieldset>

  <%= f.button :wrapped, cancel: equipment_models_path %>
<% end %>

app/views/equipment_models/edit.html.erb
<% title "Edit Equipment Model" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @equipment_model %> |
  <%= link_to "View All", equipment_models_path %> |
  <%= link_to "Delete", @equipment_model, :confirm => 'Deleting this Equipment Model will delete all related Equipment Items and Reservations. Are you sure you want to do this?', :method => :delete %>
</p>

app/views/equipment_models/index.html.erb
<% title (@category.nil? ? "Equipment Models" : @category.name.pluralize) %>

<table id="table_woo" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Name</th>
    <%= "<th>Type</th>".html_safe unless @category %>
  <%# these blank TH's necessary for the sort function %>
  <% if can? :manage, EquipmentModel %>
    <th class="no_sort"> </th>
    <th class="no_sort"> </th>
  <% end %>
  </tr>
  </thead>
  <tbody>
  <% for equipment_model in @equipment_models.includes(:category) %>
    <tr>
      <td><%= link_to equipment_model.name, equipment_model %></td>
      <%= ("<td>" + (link_to equipment_model.category.name.singularize, equipment_model.category) + "</td>").html_safe unless @category %>
      <% if can? :manage, EquipmentModel %>
        <td><%= link_to "Edit", edit_equipment_model_path(equipment_model), :class => "btn" %></td>
        <td>
          <%= make_deactivate_btn(:equipment_models,equipment_model) %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>


<div class="form-actions">
  <% if can? :manage, EquipmentModel %>
    <% if @category %>
      <%= link_to ("New "+@category.name.singularize), new_category_equipment_model_path(@category), :class => 'btn btn-primary' %>
      <%= link_to "View All Equipment Models", equipment_models_path, :class => 'btn' %>
    <% else %>
      <%= link_to "New Equipment Model", new_equipment_model_path, :class => "btn btn-primary" %>
    <% end %>
    <% if params[:show_deleted] %>
      <% if (@category.nil?) %>
        <%= link_to "Hide Deactivated Models", equipment_models_path, :class => "btn" %>
      <% else %>
        <%= link_to "Hide Deactivated Models", category_equipment_models_path(@category), :class => "btn" %>
      <% end %>
    <% else %>
      <% if (@category.nil?) %>
        <%= link_to "Show Deactivated Models", equipment_models_path(show_deleted: true), :class => "btn" %>
      <% else %>
        <%= link_to "Show Deactivated Models", category_equipment_models_path(@category, show_deleted: true), :class => "btn" %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to "Return to Catalog", catalog_path, :class => 'btn' %>
  <% end %>
</div>

app/views/equipment_models/new.html.erb
<% title "Add New " + (@category.nil? ? "Equipment Model" : @category.name.singularize) %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", (@category.nil? ? equipment_models_path : category_equipment_models_path(@category)) %></p>